### ISSUE TITLE
"bosh deploy" fails due to wrong resource_pools generated to the manifest file

### ISSUE THREAD

**Issue by funcode** [cloudfoundry-incubator/bosh-workspace#102]
When I ran "bosh deploy", I got this error:

```
/Users/pivotal/.gem/ruby/2.1.6/gems/bosh_cli-1.3169.0/lib/cli/commands/deployment.rb:126:in `block in perform': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/pivotal/.gem/ruby/2.1.6/gems/bosh_cli-1.3169.0/lib/cli/commands/deployment.rb:121:in `each'
	from /Users/pivotal/.gem/ruby/2.1.6/gems/bosh_cli-1.3169.0/lib/cli/commands/deployment.rb:121:in `perform'
	from /Users/pivotal/.gem/ruby/2.1.6/gems/bosh-workspace-0.9.7/lib/bosh/cli/commands/project_deployment.rb:42:in `deploy'
	from /Users/pivotal/.gem/ruby/2.1.6/gems/bosh_cli-1.3169.0/lib/cli/command_handler.rb:57:in `run'
	from /Users/pivotal/.gem/ruby/2.1.6/gems/bosh_cli-1.3169.0/lib/cli/runner.rb:59:in `run'
	from /Users/pivotal/.gem/ruby/2.1.6/gems/bosh_cli-1.3169.0/bin/bosh:19:in `<top (required)>'
	from /Users/pivotal/.gem/ruby/2.1.6/bin/bosh:23:in `load'
	from /Users/pivotal/.gem/ruby/2.1.6/bin/bosh:23:in `<main>'
```

It seems that the generated  .deployments/cf-warden.yml doesn't have stemcell information.
I am using the latest stemcell in cf-warden.yml:

```
stemcells:
  - name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: 3147
```

Here is the resource_pools section in the generated cf-warden manifest file:
```
3094 resource_pools:
3095 - cloud_properties:
3096     name: random
3097   name: small_z1
3098 - cloud_properties:
3099     name: random
3100   name: small_z2
3101 - cloud_properties:
3102     name: random
3103   name: medium_z1
3104 - cloud_properties:
3105     name: random
3106   name: medium_z2
3107 - cloud_properties:
3108     name: random
3109   name: large_z1
3110 - cloud_properties:
```

**Comment by funcode** [comment]
And "network" is not handled properly:

```
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 222
  Started unknown
  Started unknown > Binding deployment. Done (00:00:00)

Error 40001: Required property `network' was not specified in object ({"cloud_properties"=>{"name"=>"random"}, "name"=>"small_z1", "stemcell"=>{"name"=>"bosh-warden-boshlite-ubuntu-lucid-go_agent", "version"=>3147}})

Task 222 error

For a more detailed error report, run: bosh task 222 --debug
```

**Comment by funcode** [comment]
This is the yml file I used:

```
---
  2 name: cf-warden
  3 director_uuid: current
  4
  5 releases:
  6   - name: cf
  7     version: latest
  8     git: https://github.com/cloudfoundry/cf-release.git
  9
 10 stemcells:
 11   - name: bosh-warden-boshlite-ubuntu-trusty-go_agent
 12     version: 3147
 13
 14 templates:
 15   - cf/cf-deployment.yml
 16   - cf/cf-jobs.yml
 17   - cf/cf-properties.yml
 18   - cf/cf-infrastructure-warden.yml
 19   - cf/cf-minimal-dev.yml
 20
 21 meta:
 22   default_quota_definitions:
 23     default:
 24       memory_limit: 102400 # Increased limit for demonstration purposes
```

**Comment by funcode** [comment]
I found out the root cause -- there is a "cf/cf-resource-pools.yml" file is not included in the cf-warden.yml which I copied from the README file.

**Comment by rkoster** [comment]
@funcode thanks for spotting the issue. Could you create a PR to fix the README?

**Comment by funcode** [comment]
I've created a PR.

**Comment by rkoster** [comment]
Fixed in https://github.com/cloudfoundry-incubator/bosh-workspace/pull/106
