### ISSUE TITLE
apply deployment patch error because of git submodule

### ISSUE THREAD

**Issue by JamesClonk** [cloudfoundry-incubator/bosh-workspace#53]
bosh-workspace aborts with an error when applying a deployment patch in a bosh-workspace where there's a git submodule (the submodule is unrelated to bosh-workspace).

```
$ bundle exec bosh apply deployment patch patch/bosh.yml
/home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/gems/bosh-workspace-0.9.0.rc4/lib/bosh/cli/commands/deployment_patch.rb:69:in `add_all': 'ci/apcctl.rb' appears as both a file and a directory (Rugged::IndexError)
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/gems/bosh-workspace-0.9.0.rc4/lib/bosh/cli/commands/deployment_patch.rb:69:in `commit_all'
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/gems/bosh-workspace-0.9.0.rc4/lib/bosh/cli/commands/deployment_patch.rb:29:in `apply'
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/gems/bosh_cli-1.2922.0/lib/cli/command_handler.rb:57:in `run'
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/gems/bosh_cli-1.2922.0/lib/cli/runner.rb:56:in `run'
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/gems/bosh_cli-1.2922.0/bin/bosh:16:in `<top (required)>'
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/bin/bosh:23:in `load'
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/bin/bosh:23:in `<main>'
```

In this example I had a submodule `ci` in my bosh-workspace directory.

It seems though it actually applied the patch yml.
Upon rerunning the exact same command the error does not occur anymore.

I think bosh-workspace should not care about any possible submodules, except for the `templates`.

**Comment by rkoster** [comment]
[index.add_all](https://github.com/cloudfoundry-incubator/bosh-workspace/blob/master/lib/bosh/cli/commands/deployment_patch.rb#L69) should probably be more specific as in only add changes in `deployments` and `templates`.
