### ISSUE TITLE
prepare deployment fails because of bosh-release gocd/docker symlink

### ISSUE THREAD

**Issue by JamesClonk** [cloudfoundry-incubator/bosh-workspace#57]
bosh-workspace freaks out during `prepare deployment` on bosh-release because of a symlink (gocd/docker)

Cleaning up `.releases/` doesn't help. 
Manually git cloning the bosh release into .releases/ doesn't help either.
It seems bosh-workspace is trying to switch to some other commithash where the gocd/docker->ci/docker link then becomes broken and trips up because of this.

```
$ bundle exec bosh prepare deployment

Fetching release 'bosh' to satisfy template references
/home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/gems/rugged-0.23.0b1/lib/rugged/repository.rb:47:in `checkout_tree': Failed to make directory '/home/user/bosh-workspace/.releases/bosh/gocd/docker': No such file or directory (Rugged::OSError)
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/gems/rugged-0.23.0b1/lib/rugged/repository.rb:47:in `checkout'
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/gems/bosh-workspace-0.9.0.rc4/lib/bosh/workspace/release.rb:15:in `update_repo'
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/gems/bosh-workspace-0.9.0.rc4/lib/bosh/cli/commands/prepare.rb:32:in `block in prepare_release_repos'
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/gems/bosh-workspace-0.9.0.rc4/lib/bosh/cli/commands/prepare.rb:28:in `each'
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/gems/bosh-workspace-0.9.0.rc4/lib/bosh/cli/commands/prepare.rb:28:in `prepare_release_repos'
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/gems/bosh-workspace-0.9.0.rc4/lib/bosh/cli/commands/prepare.rb:18:in `prepare'
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/gems/bosh_cli-1.2922.0/lib/cli/command_handler.rb:57:in `run'
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/gems/bosh_cli-1.2922.0/lib/cli/runner.rb:56:in `run'
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/gems/bosh_cli-1.2922.0/bin/bosh:16:in `<top (required)>'
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/bin/bosh:23:in `load'
        from /home/user/bosh-workspace/.vendor/bundle/ruby/2.2.0/bin/bosh:23:in `<main>'
```

**Comment by rkoster** [comment]
Fixed in https://github.com/cloudfoundry-incubator/bosh-workspace/pull/61 included in [0.9.0](https://github.com/cloudfoundry-incubator/bosh-workspace/releases/tag/v0.9.0)
