### ISSUE TITLE
Undefined method 'has_key?'

### ISSUE THREAD

**Issue by fabianschwarzfritz** [cloudfoundry-incubator/bosh-workspace#72]
Hola,

after installing the bosh-workspace gem and using it with 

```
$ bosh deployment logsearch-warden
```
I get the following error
```
/Library/Ruby/Gems/2.0.0/gems/bosh-workspace-0.9.0/lib/bosh/workspace/helpers/project_deployment_helper.rb:18:in `project_deployment_file?': undefined method `has_key?' for "<%\nrequire_relative \"./lib/helper\"":String (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/bosh-workspace-0.9.0/lib/bosh/cli/commands/project_deployment.rb:18:in `set_current'
	from /Library/Ruby/Gems/2.0.0/gems/bosh_cli-1.3042.0/lib/cli/command_handler.rb:57:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/bosh_cli-1.3042.0/lib/cli/runner.rb:56:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/bosh_cli-1.3042.0/bin/bosh:19:in `<top (required)>'
	from /usr/bin/bosh:23:in `load'
	from /usr/bin/bosh:23:in `<main>'
```

Any suggestions what I am did wrong when installing the gem?

Cheers,
Fabian

**Comment by fabianschwarzfritz** [comment]
I could fix this issue with an older version of bosh-workspace that worked with our bosh workspace :+1:

**Comment by rkoster** [comment]
Should be fixed in https://github.com/cloudfoundry-incubator/bosh-workspace/pull/71
