### ISSUE TITLE
Ssh authentication not working on ubuntu

### ISSUE THREAD

**Issue by landesherr** [cloudfoundry-incubator/bosh-workspace#97]
```
staging@jumpbox:~/workspace/staging-azure$ bosh prepare deployment
Fetching release 'identity_service_broker' to satisfy template references
/var/lib/gems/2.0.0/gems/rugged-0.24.0b11/lib/rugged/repository.rb:210:in `fetch': Failed to authenticate SSH session: Unable to extract public key from private key file: Method unimplemented in libgcrypt backend (Rugged::SshError)
        from /var/lib/gems/2.0.0/gems/rugged-0.24.0b11/lib/rugged/repository.rb:210:in `fetch'
        from /var/lib/gems/2.0.0/gems/bosh-workspace-0.9.7/lib/bosh/workspace/release.rb:81:in `fetch_repo'
        from /var/lib/gems/2.0.0/gems/bosh-workspace-0.9.7/lib/bosh/workspace/release.rb:19:in `update_repo'
        from /var/lib/gems/2.0.0/gems/bosh-workspace-0.9.7/lib/bosh/cli/commands/prepare.rb:32:in `block in prepare_release_repos'
        from /var/lib/gems/2.0.0/gems/bosh-workspace-0.9.7/lib/bosh/cli/commands/prepare.rb:29:in `each'
        from /var/lib/gems/2.0.0/gems/bosh-workspace-0.9.7/lib/bosh/cli/commands/prepare.rb:29:in `prepare_release_repos'
        from /var/lib/gems/2.0.0/gems/bosh-workspace-0.9.7/lib/bosh/cli/commands/prepare.rb:19:in `prepare'
        from /var/lib/gems/2.0.0/gems/bosh_cli-1.3160.0/lib/cli/command_handler.rb:57:in `run'
        from /var/lib/gems/2.0.0/gems/bosh_cli-1.3160.0/lib/cli/runner.rb:59:in `run'
        from /var/lib/gems/2.0.0/gems/bosh_cli-1.3160.0/bin/bosh:19:in `<top (required)>'
        from /usr/local/bin/bosh:23:in `load'
        from /usr/local/bin/bosh:23:in `<main>'

staging@jumpbox:~/workspace/staging-azure$ apt-show-versions libssh2-1-dev
libssh2-1-dev:amd64/trusty 1.4.3-2 uptodate
```

**Comment by pronoiac** [comment]
The error sources to `libssh2/src/libgcrypt.c`. Elsewhere, libssh2 v 1.6.0 works without complaint. If updating isn't available, as a workaround, use `https` instead of `ssh` to [connect to private git repos.](https://github.com/cloudfoundry-incubator/bosh-workspace#using-private-boshreleases)

**Comment by rkoster** [comment]
@pronoiac thanks!
